# Generated by Django 5.0.7 on 2024-08-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post_id',
            new_name='post',
        ),
    ]
